language: python
python:
- '2.6'
- '2.7'
env:
- SH=bash
install:
- pip install -r requirements.txt
before_script:
- echo "Hello World"
- echo $SH
script:
- python setup.py sdist
- python setup.py install
deploy:
  provider: pypi
  user: sanjose
  skip_cleanup: true
  edge:
    branch: v1.8.45
  password:
    secure: fbAZCRSTNVrBUiBCk8kmXHsA+uumdTxWC56z9d3VORsm5W4oGEB45wpkIoaLTMCSN1HUUoDrWRj1LVWHzfyFuU22C2M0svddlC5dHKzEbyS5fYzSKzMK8reeNUTWKA8PaEPrXeMX30uV97epR4aYXRF1QIuuLXypYuLezX4pVv/NtWTfuayW58Q/8m4g7rGLv1LLa5jJVZgQyRCR5hcgfcSLxlrf2OCI/ivjxwXHmIChoADna/+6APfOe6FFeeVzzqwx07Vkphld52E/qzt9g/QB/qJYDo+EYnNLBuC0ATPNGzjIaJLglhI9r0volB/F44buJeE/neCW2wcCNyu9sOBHwdsJhgCgLyugvDZoI8FzhG0J6lnK79K8VtbxAZFMYYg/fUxDwOl2EQ941wd/a38EpOetA5JV/rlgELCVxxRxc5kE0enU7RY8UWeOuhSbvdd696tJTVhSp/rDFX6P1LoN4/j4GLXkCMSi0HxHf+zWiDxJfbktLbaj4yBtAf4ZAYniB7TB550qobcLQr1Kq5lvyCWpNXqkGHCs5PBc75/KM9QLXilKgrX8ocTcxipWXBiydTS6mpPMBqXgMk8SbdleriEmKwsICuK22Chd1qxW7jxNfcMCwgNtSYWpzphLQM5ew3N58bGvGCD0F5ULTSCuo3c1l/3wPXUVTtFeffs=
