language: python
python:
- '2.6'
- '2.7'
install:
- pip install -r requirements.txt
script:
- python setup.py sdist
- python setup.py install
deploy:
  provider: pypi
  user: sanjose
  password:
    secure: hVkYaGjqMSH4HAzFLJ+OBWQXE4LEq+SX3qBBRqabICOPYrHMEcy/bbxselQ2qkMLZBuWnWpIjyhgQlDAzUasDMMnCbK2Ic7fiw7DI44MD3XO6Qmm34pG9tvGSUtlfEs03ddWbiAi9/aqzT/HqEOvtDUWBto8b8OxHLetkEEybhlYxNGflk6RK9HRC1UgNg8sRD0T6JpKcsGZiM65aJWEbLwsiPprFP6l8hYiUfxtesnqomk/bJ+posDg6G95nlXbX2IZoPik22i5tUiJRCC4iYGbkvwA4Ifp90KOw/RmYeMp45EvinmRWbThZ7iA8gy7vZmnDimUpp9P7sNXUtoF+ijSDQo/kYVmka2gXoccQtfhXdQEEczaaUyO9JzQNXiG6eZYcgxlhkVIF+YEp72fjUYXajZzydIuBEnNYGSpdEVEwzjwt5So6PUE7kr7hOACRlOgZcRCI+3fe8lPhxDM394vJ8SaEaxpnkeUpgt2OjMewnL23Z0D4HLza9LnJYipcosoaBsGMMThS/+AP+NoJm6aT51NP8P/Fhj8Xk2TiwJdqoGJltB5s65JzXHSnH+M00KCDY2fEbP1CwyyGbkRnzYXycVX67Ll2RiDeLi7v/PrWg7efJr14OyHWa46zigppu55hWNcbtZt2y+B71ZdpQjyLHYVpVOdZQ2pxKbsuXM=
  skip_cleanup: true
  edge:
    branch: v1.8.45
