language: python
python:
- '2.6'
- '2.7'
install:
- pip install -r requirements.txt
script:
- python setup.py sdist
- python setup.py install
deploy:
  provider: pypi
  user: sanjose
  password:
    secure: iI3g3OjcnO7B3Ue6Q/QaRl8o2gRxPBc5Tu+400lQZ94hrkevpZpBqVRjOkOF6vkqOpzsd7hxsVEMoNOOFJpggP7IXwVIyvqVfC3ZSg7fnFDUmOzEZbrPLh+MPlEIcBcr4OP4Z6zqTscxYacPZlnoFVYALJ6ir4QgH/oJbOeaydqlnQ9xcXEZlqqgwQHTF7ZNJ3vk4wZR9roNsogkzkPOqKtZwojxHaCJXBUR1YwM83aJKDtO1mAPihfuaXBE/cbkQG2tSN+50l63uHnTObzLD8SNeCQpXfKQksovl55xtFr6nOABpFT319auqfsKmmNGhaQkIPi+Aoo6Y7MkeYI1I5vWah5vI+OiyI/lAR9Dqt6vH0Jm9yKPrqajSqXmpkVUb/KvnlLK3pvk5h+8RoSIsP3VAqkORZKSGCID14Wcq8HbUhJjtp2VylLYuK4DE2fC5ZedRcbw3Xd77JqpQ8ELb+10jgFNMBlCq/TYgD1XFODtBejDlmJK8wYlWZjLmtU6iEdWa//Xw8jc0U8pFATGw91fxtxyZh5BnFh6MUhNJDhg+puD26ur/+5JqFPiEhAP09Wg0nJxfhBJ9mfTML8Kxhuhwp4VII+7HQ/AdEDd23+0Q68BxsMSErfkW4JqVwTSJ9b7i37jsfglF3QuoCjcMsLnpxwSlOboruy7ebqYvho=
  skip_cleanup: true
  edge:
    branch: v1.8.45
