language: python
python:
- '2.6'
- '2.7'
install:
- pip install -r requirements.txt
script:
- python setup.py sdist
- python setup.py install
deploy:
  provider: pypi
  user: sanjose
  skip_cleanup: true
  edge:
    branch: v1.8.45
  password:
    secure: E9WH6xsKio7wmfOtl8ttmpaeiPsDl+7uV6JlPOVP3pb6FdhO/+oYDoMFPxD8F7ATvBVYqkdMZmP/OaofeBPMWVSSkOKbydz1FWy2GBCP8n9ddKpxSS1XBU301gusLeJMHZN0ffedSe5kFbBmjoi6UiUHsjP3yT5ogDOe5lZl6vp9DVsiD62t15Uysvu18RP9XAfN/HtA7Ng9A9AX1D2wT2aCnCHY7wzdN13I/FKsTw4VMgaNCxBQpTFi+a955ebIoV7g2gSaFvPxnfNc4s5KZzNflOWR6Q6SMMif2MhVlhi/zqy+EyQwLlZmUP7nOV10UrT9NIwaUee0jkULcWBPVscW3PNaGlDqbscADceKtFA4y4ZzHqYhXpDBPOXOuQMspqw9/+VUyAZtk7SW5zZ95DEOepuNTuAUDuKFAe00p9ynJFiDqlMXCIm6IJP+cj2+JKxrA1jnyLeolTvlpH9n6JFo5I2P450VozbHM/UC1QQNbQU6SIr2oneT4HoWg0j3I8hkAuzbt/HfFOpKqwlULo99WG3YvNuF+vVDHKgK1FHi8BABrXlZFX33sT6zYI06mKr2aWgedn/213S+iSGBscwHxt7YMTFR1XdXL6bMOSNA9B5Udj8Y1pFzq3fDGPuhUkpdiZD0RZIqqk7FAd8OoVJGjUOhBDzVTjSfuRKqUMM=
