language: python
python:
- '2.6'
- '2.7'
install:
- pip install -r requirements.txt
script:
- python setup.py sdist
- python setup.py install
deploy:
  provider: pypi
  user: sanjose
  password:
    secure: DhpkIoU9uHatDND3POfSc1zh8ZXwZ6a1bJ0Xt0mGBrMZZvFK1HjSelkApTZyYykoiFzCLR3BbfpdLpGtIkmJAuau90bhn67uo/fWnSuuwkfBkJDx+7ZnJ5Z8WtFgNii2isLdGBoccZMi2tWmaD7EoSKOeyA5ocfu/UR4BLU3jmVKIkwzIkjVLsUy0ZS60YSqnb18/OcwW0xJSLOTd+pzsOoxaPc4qocGweFyma2/I6mlJFNTCU8iq0nXOQmehTORYjk3Z1fkQ/DRQ7L4BjDGtFE0g5DN4Jxd71l1TGn9Mg8lMGzjdROOwsj5v5KvPkThl0QiQsOcoMONKwOqkJ63bIaw8hJFukF2F3mZl7Hydk2JQ6UiUTQsJV5kODxHUcEELnuWrkl07yX3QLDC8mSdT6qdW8pn7sM0FadOSVBqhI/lSgEk0FB6MhvMDiLghYJ0livF2+fo47lUMciW7wrarbphtXpexCH4dGDd6kbLvrbO523/g/BseoS8j24Wy3t+VSIrOlPB35HaqBKS3ks6gM/C0J84RwP9AtFgY6x32Nfz2BS5inmCX+V9/RTrBzXY+dvKbeiqg65uhaaISEZu6XdkcktYdtkpTAkRTdngXjCNtnROtUReILUOXpsPOkiVmOrx6lhOyQfuBXVbckeOfALf6yKOfDW2lAF0hzkRVfM=
  skip_cleanup: true
  edge:
    branch: v1.8.45
