language: python
python:
- '2.6'
- '2.7'
install:
- pip install -r requirements.txt
script:
- python setup.py sdist
- python setup.py install
deploy:
  provider: pypi
  user: sanjose
  skip_cleanup: true
  edge:
    branch: v1.8.45
  password:
    secure: FWFz0pDCsJCmYZapdTRxYS0kOGVe7qpshSHO7utHoglshggEYasDkXsus7nZC6Ib5Gj/8HkjIM2izewFjkUP4BvHftOxPF7pxGCbe/VA8mhryn+o1WTDTujKWW6IzlgVGXkrAObpNCF+HqBm/mzCuwbJmLUi3EVJWH06BajVRXJxnW+bKvbtkQfKV4i/z5GMwU1mgKs9ufEV4f6io1E5s3DizrlbDt+Lwf89AeT0D7uafHpgrMemcRH3heIZsrSpBC+qIH/tBtEmJOALC1YAuzWvGTta3Lg2IIPjuYUCFi2zaywDwpi9k0YXLbDPO+4y63dXPT6zzjI2CK2Jpcv71vxYJA87z4Ip/yihvqze3hO9m0dtclzF1Hv9Zw0y75TuO11AzteroXHCIgrumzsPeqJfz3ipa5xKlinBzqF91NP/pY2pLOfjAjb1lz1n+Htt6U/6M5scriKKxPxCi51GosPoAHVTaP0dZcK0y7qnEeNg9ISgKcxeWCbkjn5N4vJ8va7m/sdsEWpFs51tZ8530NMx34AUux+UtX5gxBhYJJlbi0bA9fb82QtBDo0K4QTLidcPja8hGFCB++22h+7NBctfFwqXFBbGZ3NmIOIzCNayZq1v0HAVfPsrfClYlVJ8Kt35rDeEa/fMPDKEpQqmqYEZ+CaBLE00QWHa1Bepwvg=
